version: 0.2

phases:
  install:
    commands:
      - cd chat-bot/lex-model
      - chmod +x gen-lex-model.sh
      - npm install -g npm@6.4.1
      - npm ci
  build:
    commands:
      - ./gen-lex-model.sh
