AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chat bot for reInvent trivia game

Parameters:
  TriviaBackendEndpoint:
    Type: String
    Default: 'https://api.reinvent-trivia.com'

Resources:
  BotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: bot.handler
      Runtime: nodejs8.10
      Timeout: 60
      Environment:
        Variables:
          API_ENDPOINT: !Ref TriviaBackendEndpoint

  LexPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt
        - BotFunction
        - Arn
      Action: "lambda:invokeFunction"
      Principal: lex.amazonaws.com
      SourceArn: !Join
        - ':'
        - - 'arn'
          - !Ref "AWS::Partition"
          - 'lex'
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - 'intent:LetsPlay:*'
